name: CI/CD Nelly Delivery

on:
  push:
    branches: [main, staging, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas Jest
        run: npm test

  deploy-prod:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Desplegar a Render (PROD)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_PROD }}

  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' && success()
    steps:
      - name: Desplegar a Render (STAGING)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_STAGING }}

  deploy-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && success()
    steps:
      - name: Desplegar a Render (DEV)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_DEV }}
